name: Build and Test BP Calculator

on:
  push:
    branches:
      # - master
      - '*'  # Run on all Branches  
  pull_request:
    branches:
        - '*'
# on:
#   push:
#     branches:
#       - main
#       - develop/*
#       - 'release/*'
jobs:
  test_infra:
    name: Test Infrastructure Deployment
    uses: ./.github/workflows/InfrastructureDeployWorkflow.yaml
    with:
      branch: update-gitactions
      run_jobs: |
        provision
        verify-profile
        delete-created-resources
      resourceGroupName: infraTest
      pipelineStage: infraVerification
    secrets: inherit
  
  deploy-dev:
    name: Build and run unit tests
    uses: ./.github/workflows/development.yml
    needs: test_infra
    with:
      branch: update-gitactions
      run_jobs: |
        build_and_unit_test
        sonar_code_scan
        bpBDD_tests
      resourceGroupName: development
      pipelineStage: devVerification
    secrets: inherit

  deploy-qa:
    name: Build and run unit tests
    uses: ./.github/workflows/qa.yml
    needs: deploy-dev
    with:
      branch: update-gitactions
      run_jobs: |
        deploy-qa-test-application
        deploy-bpCalculator
        playwright_tests
        pentesting
        delete-qa-test-application
      resourceGroupName: qa
      pipelineStage: qaVerification
    secrets: inherit

  # deploy-performance:
  #   name: Build and run unit tests
  #   uses: ./.github/workflows/performance.yml
  #   needs: deploy-qa
  #   with:
  #     branch: update-gitactions
  #     run_jobs: |
  #       deploy
  #       performance_tests
  #       pentesting
  #     resourceGroupName: qa
  #     pipelineStage: qaVerification
  #   secrets: inherit

  # deploy-production:
  #   name: Build and run unit tests
  #   uses: ./.github/workflows/performance.yml
  #   needs: deploy-performance
  #   with:
  #     branch: update-gitactions
  #     run_jobs: |
  #       deploy
  #       playwright_tests
  #       pentesting
  #     resourceGroupName: qa
  #     pipelineStage: qaVerification
  #   secrets: inherit
