name: Dev Build and Developmnent Test BP Calculator

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      run_jobs: #List of jobs to run, defaults to running all jobs if not specified
        required: false
        type: string
      resourceGroupName:
        required: true
        type: string
      pipelineStage:
        required: true
        type: string

jobs:
  build_and_unit_test:
    name: build and run unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
      - name: Build, Run Unit tests, Generate code coverage
        run: | 
          dotnet build -c Release
          dotnet test bpUnitTestProject/bpUnitTestProject.csproj --collect "XPlat Code coverage"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"./bpUnitTestProject/TestResults/*/coverage.cobertura.xml" -targetdir:"./bpUnitTestProject/coverage-report" -reporttypes:Html

      - name: Publish test results and code coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: ./bpUnitTestProject/TestResults/

      - name: Upload code coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: ./bpUnitTestProject/coverage-report/
          retention-days: 30

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: BPCA1
          scan: .
          format: ALL  # Generates all report types (HTML, XML, JSON, etc.)
          failCriteria: medium  # Fail the workflow on vulnerabilities of severity 'low' or higher
        
      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
          retention-days: 30
  
  sonar_code_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-24.04
    needs: build_and_unit_test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=fconnolly
            -Dsonar.projectKey=fconnolly_bp-ca1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        
  bpBDD_tests:
    name: Run BPValidation and BPCalculator BDD Tests
    runs-on: ubuntu-24.04
    needs: build_and_unit_test 
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Run BDD Tests
        run: |
          dotnet test AcceptanceTest/ --logger:"html;LogFileName=BDDTestResults.html" --results-directory ./AcceptanceTest/BDDTestResults

      - name: Upload bpBDD Test Results
        uses: actions/upload-artifact@v4
        with:
          name: bpBDD-test-results
          path: ./AcceptanceTest/BDDTestResults/BDDTestResults.html
          retention-days: 30
          
