# sonar_scan.yml

name: SonarCloud Security and Coverage Scanning

on:
  workflow_run:
    workflows: ["Build and Run Unit Tests"]
    types:
      - completed

jobs:
  sonar_code_scan:
    name: SonarCloud Scan with Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=fconnolly
            -Dsonar.projectKey=fconnolly_bp-ca1
            -Dsonar.cs.opencover.reportsPaths=./bpUnitTestProject/TestResults/*/coverage.cobertura.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
