name: Infrastructure Provision Test

on:
  push:
    branches:
      # - master
      - '*'  # Run on all Branches  
  pull_request:
    branches:
        - '*'
env:
  TemplateFile: azureWebAppProvisioning/webAppTemplete.json
  ParameterFile: azureWebAppProvisioning/infraTestTemplete.parameters.json
  resourceGroupName: infraTest
  subscriptionID: a0fc7782-688a-4bba-a57c-5a4896ef78d0
  region: "UK South"

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Log in to Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create Dev Resource Group
    - name: Provision Resource Group
      run: |
        az group create --name ${{ env.resourceGroupName }}ca1 --location "${{env.region}}"

    # Deploy Dev Template
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v2
      with:
        resourceGroupName: ${{ env.resourceGroupName }}ca1
        template: ${{ env.TemplateFile }}
        parameters:  ${{ env.ParameterFile }}
        region:  ${{env.region}}
        deploymentMode: Incremental

    # Download Publish Profile Artifact from 
    - name: Download Publish Profile
      run: |
        az webapp deployment list-publishing-profiles --name infraTestbp --resource-group ${{ env.resourceGroupName }}ca1 --subscription ${{ secrets.INFRA_AZURE_SUBSCRIPTION_ID}} > dev-profile.json
    
    # Upload Publish Profile Artifact
    - name: Upload Publish Profile as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish-profile
        path: dev-profile.json
  
  verify-profile:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      # Download Publish Profile Artifact
      - name: Download Publish Profile Artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-profile
          path: .

      # Verify Publish Profile
      - name: Verify Publish Profile Usability
        run: |
          PROFILE_CONTENT=$(cat dev-profile.json)
          if [ -z "$PROFILE_CONTENT" ]; then
            echo "Publish profile is empty or invalid."
            exit 1
          fi
          echo "Publish profile successfully retrieved and is not empty."
  
  delete-created-resources:
    needs: verify-profile
    runs-on: ubuntu-latest
    steps:
      # Azure Login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Delete Resource Group and all resource
      - name: Delete Resource Group
        run: |
          az group delete --name ${{ env.resourceGroupName }}ca1 -y --no-wait
          echo "Resource group deletion initiated."